- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: création du groupe tomee
  group: name=tomee

- name: création du compte pour TomEE
  user:
    name: tomee
    shell: /bin/false
    system: yes
    home: '{{tomee_home}}'
    group: tomee

- name: installation de Tomcat 8
  package: name=tomcat8 state=present
  notify:
    - déplacer l'appli web ROOT par défaut

- name: création des répertoires pour TomEE
  file:
    path: '{{tomee_home}}'
    state: directory
    owner: tomee
    group: tomee

- name: création du répertoire /opt/tomee
  file:
    path: /opt/tomee
    state: directory
    owner: tomee
    group: tomee

- name: téléchargement de tomee
  get_url:
    url: '{{tomee_url}}'
    dest: '{{tomee_dest}}'
    group: tomee
    owner: tomee

- name: extraction de l'archive
  unarchive:
    with_items:
    src: 
      - "'{{ tomee_dest }}' -C /opt/tomee --strip-components=1" 
    dest:
      - "'{{ tomee_dir }}'"

- name: donne les droits d'installation au groupe tomee
  file: path=/opt/tomee/ owner=tomee group=tomee state=directory recurse=yes

- name: droits de lecture sur le répertoire conf
  file: 
    path: /opt/tomee/conf
    group: tomee
    mode: "g+r, g+x"

- name: changement de propriétaire sur le répertoire webapps
  file:
    path: /opt/tomee/webapps
    owner: tomee
    
- name: changement de propriétaire sur le répertoire work
  file:
    path: /opt/tomee/work
    owner: tomee
    
- name: changement de propriétaire sur le répertoire temp
  file:
    path: /opt/tomee/temp
    owner: tomee

- name: changement de propriétaire sur le repertoire logs
  file:
    path: /opt/tomee/logs
    owner: tomee
    
- name: copie du fichier de déploiement pour Tomee
  template:
    src: roles/jenkins-server/templates/tomee.service
    dest: /etc/systemd/system/tomee.service
    owner: tomee
    group: tomee
  notify:
    - relancer Tomee
    
#- name: redémarrer le démon systemd
#  systemd:
#    state: restarted
#    daemon_reload: yes
#    name: tomee.service
    
#- name: démarrer le service tomee
#  systemd: state=started name=tomee.service
