- name: installation de Git
  package: name=git state=present

- name: installation de Maven
  package: name=maven state=present

- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: création du compte pour Tomcat8
  user:
    name: tomcat8
    shell: /bin/false
    system: yes
    home: '{{tomcat_home}}'

- name: création du compte pour TomEE
  user:
    name: tomee
    shell: /bin/false
    system: yes
    home: '{{tomee_home}}'

- name: installation de Tomcat 8
  package: name=tomcat8 state=present
  notify:
    - déplacer l'appli web ROOT par défaut

- name: création d'un groupe tomee
  group: name=tomee

- name: ajout de l'utilisateur tomee au groupe tomee
  user: name=tomee groupe=tomee home=/usr/share/tomee createhome=no

- name: création des répertoires pour TomEE
  file:
    path: '{{tomee_home}}'
    state: directory
    owner: tomee
    group: tomee

- name: installation de tomee
  get_url:
    url: '{{tomee_url}}'
    dest: '{{tomee_dest}}'
    group: tomee
    owner: tomee

- name: extraction de l'archive
  command: chdir=/opt/ /bin/tar xzvf /opt/apache-tomee-7.0.3-plus.tar.gz -C /opt/ creates=/opt/tomee --strip-components=1

- name: donne les droits d'installation au groupe tomee
  file: path=/opt/tomee/ owner=tomee group=tomee state=directory recurse=yes

- name: droits de lecture sur le répertoire conf
  file: 
    path: /opt/tomee/conf
    group: tomee
    mode: "g+r, g+x"

- name: changement de propriétaire sur le répertoire webapps
  file:
    path: /opt/tomee/webapps
    owner: tomee
    
- name: changement de propriétaire sur le répertoire work
  file:
    path: /opt/tomee/work
    owner: tomee
    
- name: changement de propriétaire sur le répertoire temp
  file:
    path: /opt/tomee/temp
    owner: tomee

- name: changement de propriétaire sur le repertoire logs
  file:
    path: /opt/tomee/logs
    owner: tomee
    
- name: copie du fichier de déploiement pour Tomee
  template:
    src: roles/jenkins-server/templates/context.xml
    dest: '{{tomcat_dir}}/conf/Catalina/localhost/ROOT.xml'
    owner: tomee
    group: tomee
  notify:
    - relancer Tomee


-name: configuration du fihier système pour tomee
 lineinfile: 
   name: '/etc/systemd/system/tomee.service'
   line: 'JAVA_HOME={{java_home}}'
 notify:
   - relancer Tomee

- name: copie du fichier de déploiement pour Jenkins
  template:
    src: roles/jenkins-server/templates/context.xml
    dest: '{{tomcat_dir}}/conf/Catalina/localhost/ROOT.xml'
    owner: tomcat8
    group: tomcat8
  notify:
    - relancer Tomcat
